name: Render Gantt PNG

on:
  workflow_dispatch:
  push:
    paths:
      - 'project-plan-gantt.mmd'
      - '.github/workflows/render-mermaid.yml'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CJK fonts (for Chinese text)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mermaid CLI
        run: npm i -g @mermaid-js/mermaid-cli@10.9.1

      - name: Render PNG
        run: mmdc -i project-plan-gantt.mmd -o schedule.png -b white -s 1.2

      - name: Commit PNG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schedule.png
          git commit -m "chore: render schedule.png from project-plan-gantt.mmd" || echo "No changes to commit"
          git push
